services:
  backend:
    build: .
    container_name: backend
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tutorsonDB
      - REDIS_URI=redis://redis:6379
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379